yoyogo:
  application:
    name: Blogs
    metadata: "develop"
    server:
      type: "fasthttp"
      address: ":8081"
      path: ""
      max_request_size: 2096157
      mvc:
        template: "v1/{controller}/{action}"
      static:
        patten: "/"
        webroot: "./Static"
      views:
        path: "./Static/templates"
        includes: ["",""]
  database:
    url: localhost:3306
    username: root
    password: A.jiheMA?1
  cloud:
#    discovery:
#      type: "nacos"
#      metadata:
#        url: "120.53.133.30"
#        port: 80
#        namespace: "public"
#        group_name: ""
    #    clusters: [""]
#      type: "consul"
#      metadata:
#        address: "localhost:8500"
#        health_check: "/actuator/health"
#        tags: [""]
#      type: "eureka"
#      metadata:
#        address: "http://localhost:5000/eureka"
